#\u6570\u636E\u5E93\u8FDE\u63A5\u6C60Druid

spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC\u89E3\u51B3\u65F6\u533A\u7684\u62A5\u9519
    url: jdbc:mysql://localhost:3306/student_boot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 1
      validation-query: select 1
  jackson:
    #提交的时间字符串转化为yyyy-MM-dd格式的date，返回前端时候转为yyyy-MM-dd格式的字符串
    date-format: yyyy-MM-dd


#mp\u914D\u7F6E
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

server:
  port: 8888

auth:
  ignoreUrls:
    - /manager/login

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
